import 'package:flutter/material.dart';
import 'package:expense_tracker/widgets/expenses.dart';
import 'package:flutter/services.dart';

var kColorScheme = ColorScheme.fromSeed(
  seedColor: Color.fromARGB(255, 152, 15, 177),
);

var kDarkColorScheme = ColorScheme.fromSeed(
  brightness: Brightness
      .dark, //it say that shades that has to be generated by seed color should be optimise for dark mode
  seedColor: Color.fromARGB(255, 5, 99, 125),
);

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]).then((fn) {
    runApp(
      MaterialApp(
          darkTheme: ThemeData.dark().copyWith(
            useMaterial3: true,
            colorScheme: kDarkColorScheme,
            cardTheme: CardTheme().copyWith(
              //overriding card theme with kColorTheme
              color: kDarkColorScheme.secondaryContainer,
              margin: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
            ),
            elevatedButtonTheme: ElevatedButtonThemeData(
                style: ElevatedButton.styleFrom(
              backgroundColor: kDarkColorScheme.primaryContainer,
              foregroundColor: kDarkColorScheme.onPrimaryContainer,
            )),
          ),
          theme: ThemeData().copyWith(
              useMaterial3: true,
              colorScheme: kColorScheme,
              appBarTheme: AppBarTheme().copyWith(
                backgroundColor: kColorScheme.onPrimaryContainer,
                foregroundColor: kColorScheme.primaryContainer,
              ),
              cardTheme: CardTheme().copyWith(
                //overriding card theme with kColorTheme
                color: kColorScheme.secondaryContainer,
                margin: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              ),
              elevatedButtonTheme: ElevatedButtonThemeData(
                  style: ElevatedButton.styleFrom(
                      backgroundColor: kColorScheme.primaryContainer)),
              textTheme: ThemeData().textTheme.copyWith(
                    //overiding text theme which belong to themedata object
                    titleLarge: TextStyle(
                        fontWeight: FontWeight.bold,
                        color: kColorScheme.onSecondaryContainer,
                        fontSize: 16),
                  )),
          themeMode: ThemeMode
              .system, //it is default we can ignore or there no need to mention
          home: const Expenses()),
    );
  });
}
